export const SET_PRODUCTS = "SET_PRODUCTS"
export const FILTER_PRODUCTS = "FILTER_PRODUCTS"
export const SEARCH_PRODUCTS_BY_KEYWORD = "SEARCH_PRODUCTS_BY_KEYWORD"
export const ADD_TO_CART = "ADD_TO_CART"

